<template>
  <div :class="$route.fullPath !== '/' ? '' : 'bg-nature'">
    <div class="bg-white bg-opacity-40">
      <header
        class="
          w-full
          px-6
          py-2
          bg-white
          z-40
          sticky
          top-0
          flex
          justify-between
          items-center
          border-b
          border-lightGrey
        "
        :class="showMenu ? 'bg-opacity-70': ''"
      >
        <button
          :class="showMenu ? 'container change w-max' : 'container w-max'"
          @click="showMenu = !showMenu"
        >
          <div class="bar1"></div>
          <div class="bar2"></div>
          <div class="bar3"></div>
        </button>
        <NuxtLink to="/" class="text-lg text-center font-semibold">Wong801 Portfolio</NuxtLink>
        <NuxtLink v-if="!$cookies.get('jwt')" to="/login">Login</NuxtLink>
        <button v-else @click="handleLogout">Logout</button>
      </header>
      <nuxt-link
        v-if="$route.fullPath !== '/' && !$cookies.get('jwt') && !showMenu"
        to="/"
        class="underline px-4"
        >Back to home</nuxt-link
      >
      <div
        v-if="showMenu"
        class="py-4 px-10 w-full lg:w-1/5 z-30 bg-white h-full slide-in-left fixed"
      >
        <div class="sticky top-0 h-full flex flex-col text-center gap-y-6">
          <nuxt-link to="/" class="border-b py-1"> Home </nuxt-link>
          <div
            v-if="!$cookies.get('jwt')"
            class="flex flex-col gap-y-6 text-center"
          >
            <nuxt-link to="/login" class="border-b py-1"> Login </nuxt-link>
            <nuxt-link to="/register" class="border-b py-1"> Register </nuxt-link>
          </div>
          <div v-else>

          </div>
          <div class="h-full flex flex-col justify-end">
            <nuxt-link to="/about">About</nuxt-link>
          </div>
        </div>
      </div>
      <div
        :class="
          showMenu
            ? 'fixed overflow-x-hidden overflow-y-auto inset-0 flex justify-center items-center z-20 bg-black bg-opacity-70 '
            : ''
        "
        @click="showMenu = !showMenu"
      ></div>
      <Nuxt class="min-h-screen"/>
      <footer class="w-full inset-x-0 bottom-0">
        <div class="text-center">
          <a href="https://github.com/Wong801" target="_blank">Github</a>
        </div>
        <div class="py-1 bg-lightGrey">
          <p class="text-center text-darkGrey font-bold">
            &copy; {{ new Date().getFullYear() }} Wong801
          </p>
        </div>
      </footer>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      showMenu: false,
    }
  },
  methods: {
    handleLogout() {
      this.$store.dispatch('api/user/logout').then((res) => {
        this.$cookies.remove('jwt')
        this.$router.push('/')
        this.$toast.success(res.data.msg)
      })
    },
  },
}
</script>

<style scoped>
.bg-nature {
  background: none;
}

@media only screen and (min-width: 1280px) {
  .bg-nature {
    background-image: url('@/static/img/bg-forest.jpg');
    background-size: 100% auto;
    background-attachment: fixed;
    background-repeat: no-repeat;
  }
}

.nuxt-link-exact-active {
  font-weight: 600;
  text-decoration: underline;
}

.container {
  display: inline-block;
  cursor: pointer;
}

.bar1,
.bar2,
.bar3 {
  width: 35px;
  height: 5px;
  background-color: #333;
  margin: 6px 0;
  transition: 0.4s;
}

.change .bar1 {
  -webkit-transform: rotate(-45deg) translate(-9px, 6px);
  transform: rotate(-45deg) translate(-9px, 6px);
}

.change .bar2 {
  opacity: 0;
}

.change .bar3 {
  -webkit-transform: rotate(45deg) translate(-8px, -8px);
  transform: rotate(45deg) translate(-8px, -8px);
}

.slide-in-left {
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    forwards;
  animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-8-15 19:56:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>
